### PR TITLE
Fix Flake8 error "E741 ambiguous variable name 'O"

### PR DESCRIPTION
**Pull request by cool-RR**

### CODE REVIEW

**Comment by cool-RR** [comment]
@Jamesfox1 This might fix the Flake8 problem. It says "1 workflow awaiting approval". Can you approve running the workflow to see whether it passes?

**Comment by Jamesfox1** [comment]
> @Jamesfox1 This might fix the Flake8 problem. It says "1 workflow awaiting approval". Can you approve running the workflow to see whether it passes?

Does it pass the flake8 test locally? i.e., when you run `[tests/check-code.sh](https://github.com/causalincentives/pycid/blob/master/tests/check-code.sh)`?

**Comment by Jamesfox1** [comment]
> Yes, flake8 passes locally. Lots of MyPy errors but I won't dive into those.

Okay, thanks! As said above, I'll wait until the weekend to look into this!

**Comment by cool-RR** [comment]
🦗

**Pull request merged**
